### PR TITLE
Update readme to support new module definition

### PR DESCRIPTION
**Pull request by CCali93**

### CODE REVIEW

**Comment by Santinell** [comment]
Looks good, but this example must say what this format is optional,
so better will create a two examples - simple (one level) and complex (with submodules)

**Comment by CCali93** [comment]
@Santinell I've updated the readme to include those changes, let me know what you think.

**Comment by Santinell** [comment]
I add you in CONTRIBUTORS.md

**Comment by CCali93** [comment]
Thank you :)

**Pull request merged**
