### PR TITLE
Fix bug with invalid response id for number 0

### PR DESCRIPTION
**Pull request by CCali93**
PR for the #5 issue I created. Let me know what you think

### CODE REVIEW

**Comment by Santinell** [comment]
Not bad ^_^ 
But thats not only place there checking call.id
I thing is better write only one check in handleSingle method

**Comment by CCali93** [comment]
Hey @Santinell I think I've covered my bases a little better this time, and added some extra tests for error cases. Also i added coverage to .gitignore so that never gets committed if the coverage is run locally.

**Comment by Santinell** [comment]
Thanks for your work!

**Comment by CCali93** [comment]
No Problem, @Santinell

**Pull request merged**
